// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package api

import "fmt"
import "encoding/json"

// Schema definition to drop off a journey
type DropOffRqJson struct {
	// group id
	Id int `json:"id"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DropOffRqJson) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["id"]; !ok || v == nil {
		return fmt.Errorf("field id: required")
	}
	type Plain DropOffRqJson
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = DropOffRqJson(plain)
	return nil
}
