name: Run unit tests when open a pull request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests
        run: make test-unit
      - name: Check test results
        if: ${{ success() }}
        run: |
          # Add a comment to the PR indicating the tests passed
          echo "All tests passed"

